create table if not exists public.demo_groups (
  id bigint generated by default as identity primary key,
  name text unique not null,
  type text not null default 'Public',
  member_count integer,
  member_count_label text,
  note text,
  icon text,
  style text,
  description text,
  is_demo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.demo_groups add column if not exists type text not null default 'Public';
alter table public.demo_groups add column if not exists member_count integer;
alter table public.demo_groups add column if not exists member_count_label text;
alter table public.demo_groups add column if not exists note text;
alter table public.demo_groups add column if not exists icon text;
alter table public.demo_groups add column if not exists style text;
alter table public.demo_groups add column if not exists description text;
alter table public.demo_groups add column if not exists is_demo boolean default true;
alter table public.demo_groups add column if not exists updated_at timestamptz default now();

alter table public.demo_groups enable row level security;

drop policy if exists "Demo visitors can view demo groups" on public.demo_groups;
create policy "Demo visitors can view demo groups"
on public.demo_groups for select
to anon, authenticated
using (is_demo = true);
