create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text default 'community',
  tag text,
  tags text[] default '{}',
  venue_name text,
  venue text,
  neighborhood text,
  area text,
  date date,
  time text,
  price text,
  starts_at timestamptz,
  ends_at timestamptz,
  timezone text default 'America/New_York',
  price_min numeric,
  price_max numeric,
  ticket_url text,
  image_url text,
  is_free boolean default false,
  venue_address text,
  source text not null default 'manual',
  external_id text,
  external_url text,
  latitude double precision,
  longitude double precision,
  lat double precision,
  lng double precision,
  lokal_score integer default 50,
  raw_json jsonb,
  status text default 'published',
  last_seen_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.events add column if not exists title text;
alter table public.events add column if not exists description text;
alter table public.events add column if not exists category text default 'community';
alter table public.events add column if not exists tag text;
alter table public.events add column if not exists tags text[] default '{}';
alter table public.events add column if not exists venue_name text;
alter table public.events add column if not exists venue text;
alter table public.events add column if not exists neighborhood text;
alter table public.events add column if not exists area text;
alter table public.events add column if not exists date date;
alter table public.events add column if not exists time text;
alter table public.events add column if not exists price text;
alter table public.events add column if not exists starts_at timestamptz;
alter table public.events add column if not exists ends_at timestamptz;
alter table public.events add column if not exists timezone text default 'America/New_York';
alter table public.events add column if not exists price_min numeric;
alter table public.events add column if not exists price_max numeric;
alter table public.events add column if not exists ticket_url text;
alter table public.events add column if not exists image_url text;
alter table public.events add column if not exists is_free boolean default false;
alter table public.events add column if not exists venue_address text;
alter table public.events add column if not exists source text not null default 'manual';
alter table public.events add column if not exists external_id text;
alter table public.events add column if not exists external_url text;
alter table public.events add column if not exists latitude double precision;
alter table public.events add column if not exists longitude double precision;
alter table public.events add column if not exists lat double precision;
alter table public.events add column if not exists lng double precision;
alter table public.events add column if not exists lokal_score integer default 50;
alter table public.events add column if not exists raw_json jsonb;
alter table public.events add column if not exists status text default 'published';
alter table public.events add column if not exists last_seen_at timestamptz default now();
alter table public.events add column if not exists created_at timestamptz default now();
alter table public.events add column if not exists updated_at timestamptz default now();

drop index if exists public.events_source_external_id_key;
create unique index events_source_external_id_key
on public.events (source, external_id);

create index if not exists events_starts_at_idx on public.events (starts_at);
create index if not exists events_category_idx on public.events (category);
create index if not exists events_status_idx on public.events (status);
create index if not exists events_tags_gin_idx on public.events using gin (tags);

alter table public.events enable row level security;

drop policy if exists "Anyone can view active events" on public.events;
create policy "Anyone can view active events"
on public.events for select
to anon, authenticated
using (true);
