create table if not exists public.event_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  event_id bigint not null references public.events(id) on delete cascade,
  created_at timestamptz default now()
);

create index if not exists event_interactions_user_id_idx on public.event_interactions (user_id);
create index if not exists event_interactions_event_id_idx on public.event_interactions (event_id);
create unique index if not exists event_interactions_user_event_key on public.event_interactions (user_id, event_id);

alter table public.event_interactions enable row level security;

drop policy if exists "Users can view their event interactions" on public.event_interactions;
create policy "Users can view their event interactions"
on public.event_interactions for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can save event interactions" on public.event_interactions;
create policy "Users can save event interactions"
on public.event_interactions for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove event interactions" on public.event_interactions;
create policy "Users can remove event interactions"
on public.event_interactions for delete
to authenticated
using ((select auth.uid()) = user_id);
