create table if not exists public.happy_hours (
  id bigint generated by default as identity primary key,
  source_key text unique not null,
  venue_name text not null,
  venue_address text not null,
  neighborhood text,
  weekday smallint not null check (weekday between 0 and 6),
  starts_at time not null,
  ends_at time not null,
  title text,
  specials text,
  price_label text,
  tags text[] default array['Happy hour', 'Food & Drink'],
  source_name text not null default 'venue-official',
  source_url text not null,
  source_updated_at timestamptz,
  verified_at timestamptz default now(),
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists happy_hours_active_weekday_idx
on public.happy_hours (is_active, weekday, starts_at);

alter table public.happy_hours enable row level security;

drop policy if exists "Anyone can view active happy hours" on public.happy_hours;
create policy "Anyone can view active happy hours"
on public.happy_hours for select
to anon, authenticated
using (is_active = true);
