create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  venue_type text,
  neighborhood text,
  phone text,
  email text,
  contact_method text,
  instagram_url text,
  website_url text,
  source_name text not null default 'venue-import',
  raw_data jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, address)
);

create index if not exists venues_neighborhood_idx on public.venues (neighborhood);
create index if not exists venues_type_idx on public.venues (venue_type);

alter table public.venues enable row level security;
