create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  name text not null,
  address text,
  venue_type text,
  neighborhood text,
  phone text,
  email text,
  contact_method text,
  instagram_url text,
  website_url text,
  source_name text not null default 'venue-import',
  raw_data jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, address)
);

create index if not exists venues_neighborhood_idx on public.venues (neighborhood);
create index if not exists venues_type_idx on public.venues (venue_type);

alter table public.venues add column if not exists source_key text;
alter table public.venues alter column address drop not null;

update public.venues
set source_key = lower(regexp_replace(concat_ws('|', name, coalesce(address, neighborhood, '')), '[^a-z0-9]+', '-', 'g'))
where source_key is null;

alter table public.venues alter column source_key set not null;
create unique index if not exists venues_source_key_idx on public.venues (source_key);

alter table public.venues enable row level security;
