create table if not exists public.account_deletion_requests (
  id bigint generated by default as identity primary key,
  user_key text not null,
  account_type text not null default 'person',
  full_name text,
  username text,
  email text,
  phone text,
  reason text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists account_deletion_requests_user_key_idx
  on public.account_deletion_requests(user_key);

create index if not exists account_deletion_requests_status_idx
  on public.account_deletion_requests(status);

alter table public.account_deletion_requests enable row level security;

drop policy if exists "Anyone can request account deletion"
  on public.account_deletion_requests;

create policy "Anyone can request account deletion"
  on public.account_deletion_requests
  for insert
  to anon, authenticated
  with check (true);
