create table if not exists public.app_invites (
  id bigint generated by default as identity primary key,
  inviter_user_key text not null,
  inviter_name text,
  inviter_username text,
  invite_code text not null,
  invite_url text not null,
  channel text not null default 'copy',
  created_at timestamptz not null default now()
);

create index if not exists app_invites_inviter_user_key_idx
  on public.app_invites(inviter_user_key);

create index if not exists app_invites_invite_code_idx
  on public.app_invites(invite_code);

alter table public.app_invites enable row level security;

drop policy if exists "Anyone can record app invites"
  on public.app_invites;

create policy "Anyone can record app invites"
  on public.app_invites
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Anyone can look up app invites"
  on public.app_invites;

create policy "Anyone can look up app invites"
  on public.app_invites
  for select
  to anon, authenticated
  using (true);

create table if not exists public.app_referrals (
  id bigint generated by default as identity primary key,
  invite_code text not null,
  inviter_user_key text not null,
  inviter_name text,
  invited_user_key text not null,
  invited_name text,
  invited_username text,
  invited_email text,
  status text not null default 'joined',
  points_awarded integer not null default 5,
  created_at timestamptz not null default now()
);

alter table public.app_referrals
  alter column points_awarded set default 5;

update public.app_referrals
  set points_awarded = 5
  where points_awarded = 3;

create unique index if not exists app_referrals_invite_invited_user_idx
  on public.app_referrals(invite_code, invited_user_key);

create index if not exists app_referrals_inviter_user_key_idx
  on public.app_referrals(inviter_user_key);

alter table public.app_referrals enable row level security;

drop policy if exists "Anyone can record app referrals"
  on public.app_referrals;

create policy "Anyone can record app referrals"
  on public.app_referrals
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Anyone can read app referrals"
  on public.app_referrals;

create policy "Anyone can read app referrals"
  on public.app_referrals
  for select
  to anon, authenticated
  using (true);
