create table if not exists public.app_action_events (
  id bigint generated by default as identity primary key,
  user_key text not null,
  action_type text not null,
  route text,
  profile_name text,
  account_type text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists app_action_events_user_key_idx
  on public.app_action_events(user_key);

create index if not exists app_action_events_action_type_idx
  on public.app_action_events(action_type);

alter table public.app_action_events enable row level security;

drop policy if exists "Anyone can record app actions"
  on public.app_action_events;

create policy "Anyone can record app actions"
  on public.app_action_events
  for insert
  to anon, authenticated
  with check (true);
