create table if not exists public.event_attendance_receipts (
  id bigint generated by default as identity primary key,
  user_key text not null,
  event_key text not null,
  title text not null default '',
  venue text not null default '',
  category text not null default '',
  event_time text not null default '',
  attended_at timestamptz not null default now(),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists event_attendance_receipts_user_event_idx
  on public.event_attendance_receipts (user_key, event_key);

create index if not exists event_attendance_receipts_user_attended_idx
  on public.event_attendance_receipts (user_key, attended_at desc);

alter table public.event_attendance_receipts enable row level security;

grant select, insert, update on public.event_attendance_receipts to anon, authenticated;

drop policy if exists "event_attendance_receipts_select_demo" on public.event_attendance_receipts;
create policy "event_attendance_receipts_select_demo"
  on public.event_attendance_receipts for select
  to anon, authenticated
  using (true);

drop policy if exists "event_attendance_receipts_insert_demo" on public.event_attendance_receipts;
create policy "event_attendance_receipts_insert_demo"
  on public.event_attendance_receipts for insert
  to anon, authenticated
  with check (true);

drop policy if exists "event_attendance_receipts_update_demo" on public.event_attendance_receipts;
create policy "event_attendance_receipts_update_demo"
  on public.event_attendance_receipts for update
  to anon, authenticated
  using (true)
  with check (true);
