create table if not exists public.feedback_submissions (
  id bigint generated by default as identity primary key,
  user_key text not null,
  account_type text not null default 'person',
  full_name text,
  username text,
  email text,
  phone text,
  route text,
  context text,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists feedback_submissions_user_key_idx
  on public.feedback_submissions(user_key);

create index if not exists feedback_submissions_status_created_idx
  on public.feedback_submissions(status, created_at desc);

alter table public.feedback_submissions enable row level security;

grant select, insert, update on public.feedback_submissions to anon, authenticated;

drop policy if exists "feedback_submissions_insert_demo"
  on public.feedback_submissions;

create policy "feedback_submissions_insert_demo"
  on public.feedback_submissions
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "feedback_submissions_select_demo"
  on public.feedback_submissions;

create policy "feedback_submissions_select_demo"
  on public.feedback_submissions
  for select
  to authenticated
  using (true);

drop policy if exists "feedback_submissions_update_demo"
  on public.feedback_submissions;

create policy "feedback_submissions_update_demo"
  on public.feedback_submissions
  for update
  to authenticated
  using (true)
  with check (true);
