-- Import: refreshed Washington, D.C. neighborhood BID events (generated 2026-07-24)
-- Re-scraped from the BID calendars (Downtown DC, Mount Vernon Triangle, Georgetown,
-- Union Market, Capitol Riverfront/Navy Yard, Southwest) for occurrences 2026-07-24 .. 2026-09-15.
-- Excludes Nationals/D.C. United/Washington Spirit games (already in 'ticketmaster') and
-- FRESHFARM/CHoP/Stacks farmers markets (already in 'farmers-markets').
-- Addresses carry explicit "Washington, DC" + quadrant so the enforce_dc_events trigger
-- keeps rows published. Idempotent via unique (source, external_id) -- safe to re-run.

insert into public.events (
  source, external_id, title, description, category, tag, tags,
  venue_name, venue, venue_address, neighborhood, date, time, starts_at,
  price, ticket_url, external_url, is_free
) values  ('Downtown DC BID','bid_downtown_ringside_at_anthem_row_2026-07-25','Ringside at Anthem Row','Ringside boxing entertainment and live programming on Anthem Row downtown.','community','Community',array['Downtown'],'Anthem Row','Anthem Row','Anthem Row, 700 6th St NW, Washington, DC','Downtown',date '2026-07-25','3:00 PM',(timestamp '2026-07-25 15:00:00' at time zone 'America/New_York'),null,'https://www.downtowndc.org/events/ringside-at-anthem-row/','https://www.downtowndc.org/events/ringside-at-anthem-row/',false),
  ('Downtown DC BID','bid_downtown_downtowndc_live_at_anthem_row_2026-07-30','DowntownDC Live! at Anthem Row','Free live music and entertainment series on Anthem Row.','concerts','Concerts',array['Downtown','Free'],'Anthem Row','Anthem Row','Anthem Row, 700 6th St NW, Washington, DC','Downtown',date '2026-07-30','5:00 PM',(timestamp '2026-07-30 17:00:00' at time zone 'America/New_York'),'Free','https://www.downtowndc.org/events/downtowndc-live-at-anthem-row/','https://www.downtowndc.org/events/downtowndc-live-at-anthem-row/',true),
  ('Mount Vernon Triangle CID','bid_mvt_july_vinyl_sets_at_la_betty_2026-07-24','July Vinyl Sets at la Betty','Vinyl DJ sets on the patio at la Betty every Friday and Saturday, 8pm-12am.','nightlife','Nightlife',array['Mount Vernon Triangle','Free'],'la Betty','la Betty','la Betty, Mount Vernon Triangle, Washington, DC','Mount Vernon Triangle',date '2026-07-24','8:00 PM',(timestamp '2026-07-24 20:00:00' at time zone 'America/New_York'),'Free','https://www.mountvernontriangle.org/event/july-vinyl-sets-at-la-betty-6/','https://www.mountvernontriangle.org/event/july-vinyl-sets-at-la-betty-6/',true),
  ('Mount Vernon Triangle CID','bid_mvt_july_vinyl_sets_at_la_betty_2026-07-25','July Vinyl Sets at la Betty','Vinyl DJ sets on the patio at la Betty every Friday and Saturday, 8pm-12am.','nightlife','Nightlife',array['Mount Vernon Triangle','Free'],'la Betty','la Betty','la Betty, Mount Vernon Triangle, Washington, DC','Mount Vernon Triangle',date '2026-07-25','8:00 PM',(timestamp '2026-07-25 20:00:00' at time zone 'America/New_York'),'Free','https://www.mountvernontriangle.org/event/july-vinyl-sets-at-la-betty-6/','https://www.mountvernontriangle.org/event/july-vinyl-sets-at-la-betty-6/',true),
  ('Mount Vernon Triangle CID','bid_mvt_july_vinyl_sets_at_la_betty_2026-07-31','July Vinyl Sets at la Betty','Vinyl DJ sets on the patio at la Betty every Friday and Saturday, 8pm-12am.','nightlife','Nightlife',array['Mount Vernon Triangle','Free'],'la Betty','la Betty','la Betty, Mount Vernon Triangle, Washington, DC','Mount Vernon Triangle',date '2026-07-31','8:00 PM',(timestamp '2026-07-31 20:00:00' at time zone 'America/New_York'),'Free','https://www.mountvernontriangle.org/event/july-vinyl-sets-at-la-betty-6/','https://www.mountvernontriangle.org/event/july-vinyl-sets-at-la-betty-6/',true),
  ('Mount Vernon Triangle CID','bid_mvt_movelove_a_musical_kiss_to_the_community_2026-07-24','MOVELOVE: A Musical Kiss to the Community','A late-night music celebration curated by Tony Salano & the Freespirits with DJ Jahsonic.','nightlife','Nightlife',array['Mount Vernon Triangle','Free'],'Mount Vernon Triangle','Mount Vernon Triangle','Mount Vernon Triangle, Washington, DC','Mount Vernon Triangle',date '2026-07-24','9:00 PM',(timestamp '2026-07-24 21:00:00' at time zone 'America/New_York'),'Free','https://www.mountvernontriangle.org/event/movelove-a-musical-kiss-to-the-community-curated-by-tony-salano-the-freespirits-and-dj-jahsonic/','https://www.mountvernontriangle.org/event/movelove-a-musical-kiss-to-the-community-curated-by-tony-salano-the-freespirits-and-dj-jahsonic/',true),
  ('Georgetown BID','bid_gtown_sip_and_fold_summer_origami_with_naoko_kamioka_2026-07-24','Sip and Fold Summer Origami with Naoko Kamioka','A relaxed sip-and-fold summer origami workshop with artist Naoko Kamioka.','community','Community',array['Georgetown'],'Washington Printmakers Gallery','Washington Printmakers Gallery','Washington Printmakers Gallery, 1641 Wisconsin Ave NW, Washington, DC','Georgetown',date '2026-07-24','5:30 PM',(timestamp '2026-07-24 17:30:00' at time zone 'America/New_York'),null,'https://www.georgetowndc.com/event/sip-and-fold-summer-origami-with-naoko-kamioka/','https://www.georgetowndc.com/event/sip-and-fold-summer-origami-with-naoko-kamioka/',false),
  ('Georgetown BID','bid_gtown_washington_harbour_waterfront_movie_series_2026-07-24','Washington Harbour Waterfront Movie Series','A free outdoor film screening along the Georgetown waterfront.','community','Community',array['Georgetown','Free'],'Georgetown Waterfront Park','Georgetown Waterfront Park','Georgetown Waterfront Park, K St NW, Washington, DC','Georgetown',date '2026-07-24','7:00 PM',(timestamp '2026-07-24 19:00:00' at time zone 'America/New_York'),'Free','https://www.georgetowndc.com/event/washington-harbour-waterfront-movie-series/2026-07-24/','https://www.georgetowndc.com/event/washington-harbour-waterfront-movie-series/2026-07-24/',true),
  ('Georgetown BID','bid_gtown_dancing_on_the_waterfront_summer_series_2026-07-28','Dancing on the Waterfront: Summer Series','A summer evening dance series on the Georgetown waterfront.','community','Community',array['Georgetown','Free'],'Georgetown Waterfront','Georgetown Waterfront','Georgetown Waterfront, K St NW, Washington, DC','Georgetown',date '2026-07-28','6:00 PM',(timestamp '2026-07-28 18:00:00' at time zone 'America/New_York'),'Free','https://www.georgetowndc.com/event/dancing-waterfront/','https://www.georgetowndc.com/event/dancing-waterfront/',true),
  ('Georgetown BID','bid_gtown_dancing_on_the_waterfront_summer_series_2026-08-04','Dancing on the Waterfront: Summer Series','A summer evening dance series on the Georgetown waterfront.','community','Community',array['Georgetown','Free'],'Georgetown Waterfront','Georgetown Waterfront','Georgetown Waterfront, K St NW, Washington, DC','Georgetown',date '2026-08-04','6:00 PM',(timestamp '2026-08-04 18:00:00' at time zone 'America/New_York'),'Free','https://www.georgetowndc.com/event/dancing-waterfront/','https://www.georgetowndc.com/event/dancing-waterfront/',true),
  ('Union Market District','bid_union_spanish_tapas_with_a_modern_twist_2026-07-24','Spanish Tapas with a Modern Twist','A hands-on Spanish tapas cooking class with Chef Troy at Union Market.','food','Food',array['Union Market'],'Union Market District','Union Market District','Union Market, 1309 5th St NE, Washington, DC','Union Market',date '2026-07-24','6:30 PM',(timestamp '2026-07-24 18:30:00' at time zone 'America/New_York'),null,'https://unionmarketdc.com/event/spanish-tapas-with-a-modern-twist/2026-07-24/','https://unionmarketdc.com/event/spanish-tapas-with-a-modern-twist/2026-07-24/',false),
  ('Union Market District','bid_union_peruvian_independence_day_at_la_cosecha_2026-07-25','Peruvian Independence Day at La Cosecha','Celebrate Peruvian Independence Day with Peruvian Brothers at La Cosecha.','festivals','Festivals',array['Union Market'],'La Cosecha','La Cosecha','La Cosecha, 1280 4th St NE, Washington, DC','Union Market',date '2026-07-25','1:00 PM',(timestamp '2026-07-25 13:00:00' at time zone 'America/New_York'),null,'https://unionmarketdc.com/event/peruvian-independence-day-2/','https://unionmarketdc.com/event/peruvian-independence-day-2/',false),
  ('Union Market District','bid_union_pet_portraits_at_salt_and_sundry_2026-07-25','Pet Portraits at Salt & Sundry','Sit for a hand-painted pet portrait at Salt & Sundry.','community','Community',array['Union Market'],'Salt & Sundry','Salt & Sundry','Salt & Sundry, 1309 5th St NE, Washington, DC','Union Market',date '2026-07-25','1:00 PM',(timestamp '2026-07-25 13:00:00' at time zone 'America/New_York'),null,'https://unionmarketdc.com/event/pet-portraits-at-salt-sundry/','https://unionmarketdc.com/event/pet-portraits-at-salt-sundry/',false),
  ('Union Market District','bid_union_artist_collaboration_series_cantstopgoodboy_for_saint_helens_leatherworks_2026-07-25','Artist Collaboration Series: CANTSTOPGOODBOY for Saint Helens Leatherworks','An artist collaboration event with CANTSTOPGOODBOY at Saint Helens Leatherworks.','community','Community',array['Union Market'],'Saint Helens Leatherworks','Saint Helens Leatherworks','Saint Helens Leatherworks, 1309 5th St NE, Washington, DC','Union Market',date '2026-07-25','6:00 PM',(timestamp '2026-07-25 18:00:00' at time zone 'America/New_York'),null,'https://unionmarketdc.com/event/artist-collaboration-series-cantstopgoodboy-for-saint-helens-leatherworks/','https://unionmarketdc.com/event/artist-collaboration-series-cantstopgoodboy-for-saint-helens-leatherworks/',false),
  ('Union Market District','bid_union_apapacho_2_year_anniversary_2026-08-01','Apapacho 2-Year Anniversary','Apapacho celebrates its two-year anniversary with food and festivities.','community','Community',array['Union Market'],'Apapacho','Apapacho','Apapacho, 1280 4th St NE, Washington, DC','Union Market',date '2026-08-01','2:00 PM',(timestamp '2026-08-01 14:00:00' at time zone 'America/New_York'),null,'https://unionmarketdc.com/event/apapacho-2-year-anniversary/','https://unionmarketdc.com/event/apapacho-2-year-anniversary/',false),
  ('Capitol Riverfront BID','bid_riverfront_friday_night_concert_series_ft_the_bgx_band_ft_kashi_tara_2026-07-24','Friday Night Concert Series ft. the BGX Band ft. Kashi-Tara','Free R&B, neo-soul and funk on the Yards Park boardwalk with river views.','concerts','Concerts',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-07-24','6:30 PM',(timestamp '2026-07-24 18:30:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/friday-night-concert-series-jul-25-2026','https://navyyarddc.org/event/friday-night-concert-series-jul-25-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_country_wednesday_at_takoda_2026-07-29','Country Wednesday at Takoda','Country music night at Takoda with bucket specials, cornhole and live entertainment.','concerts','Concerts',array['Navy Yard'],'Takoda Navy Yard','Takoda Navy Yard','Takoda, 1280 4th St SE, Washington, DC','Navy Yard',date '2026-07-29','5:00 PM',(timestamp '2026-07-29 17:00:00' at time zone 'America/New_York'),null,'https://navyyarddc.org/event/country-wednesday-at-takoda-3','https://navyyarddc.org/event/country-wednesday-at-takoda-3',false),
  ('Capitol Riverfront BID','bid_riverfront_country_wednesday_at_takoda_2026-08-05','Country Wednesday at Takoda','Country music night at Takoda with bucket specials, cornhole and live entertainment.','concerts','Concerts',array['Navy Yard'],'Takoda Navy Yard','Takoda Navy Yard','Takoda, 1280 4th St SE, Washington, DC','Navy Yard',date '2026-08-05','5:00 PM',(timestamp '2026-08-05 17:00:00' at time zone 'America/New_York'),null,'https://navyyarddc.org/event/country-wednesday-at-takoda-3','https://navyyarddc.org/event/country-wednesday-at-takoda-3',false),
  ('Capitol Riverfront BID','bid_riverfront_dpr_movies_on_the_great_lawn_super_mario_brothers_2026-07-30','DPR Movies on the Great Lawn: Super Mario Brothers','Free family movie night on the Great Lawn with themed activities.','community','Community',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-07-30','6:00 PM',(timestamp '2026-07-30 18:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/dpr-movies-on-the-great-lawn-super-mario-brothers','https://navyyarddc.org/event/dpr-movies-on-the-great-lawn-super-mario-brothers',true),
  ('Capitol Riverfront BID','bid_riverfront_live_music_at_dacha_navy_yard_2026-07-30','Live Music at Dacha Navy Yard','Thursday live music at Dacha''s riverfront beer garden.','concerts','Concerts',array['Navy Yard'],'Dacha Navy Yard','Dacha Navy Yard','Dacha Navy Yard, 79 Potomac Ave SE, Washington, DC','Navy Yard',date '2026-07-30',null,null,null,'https://navyyarddc.org/event/live-music-at-dacha-navy-yard-2','https://navyyarddc.org/event/live-music-at-dacha-navy-yard-2',false),
  ('Capitol Riverfront BID','bid_riverfront_movies_on_the_pitch_at_audi_field_2026-07-30','Movies on the Pitch at Audi Field','Family-friendly outdoor cinema on the Audi Field pitch.','community','Community',array['Navy Yard','Free'],'Audi Field','Audi Field','Audi Field, 100 Potomac Ave SW, Washington, DC','Navy Yard',date '2026-07-30','7:00 PM',(timestamp '2026-07-30 19:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/movies-on-the-pitch','https://navyyarddc.org/event/movies-on-the-pitch',true),
  ('Capitol Riverfront BID','bid_riverfront_movies_on_the_pitch_at_audi_field_2026-08-06','Movies on the Pitch at Audi Field','Family-friendly outdoor cinema on the Audi Field pitch.','community','Community',array['Navy Yard','Free'],'Audi Field','Audi Field','Audi Field, 100 Potomac Ave SW, Washington, DC','Navy Yard',date '2026-08-06','7:00 PM',(timestamp '2026-08-06 19:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/movies-on-the-pitch','https://navyyarddc.org/event/movies-on-the-pitch',true),
  ('Capitol Riverfront BID','bid_riverfront_movies_on_the_pitch_at_audi_field_2026-08-13','Movies on the Pitch at Audi Field','Family-friendly outdoor cinema on the Audi Field pitch.','community','Community',array['Navy Yard','Free'],'Audi Field','Audi Field','Audi Field, 100 Potomac Ave SW, Washington, DC','Navy Yard',date '2026-08-13','7:00 PM',(timestamp '2026-08-13 19:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/movies-on-the-pitch','https://navyyarddc.org/event/movies-on-the-pitch',true),
  ('Capitol Riverfront BID','bid_riverfront_movies_on_the_pitch_at_audi_field_2026-08-20','Movies on the Pitch at Audi Field','Family-friendly outdoor cinema on the Audi Field pitch.','community','Community',array['Navy Yard','Free'],'Audi Field','Audi Field','Audi Field, 100 Potomac Ave SW, Washington, DC','Navy Yard',date '2026-08-20','7:00 PM',(timestamp '2026-08-20 19:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/movies-on-the-pitch','https://navyyarddc.org/event/movies-on-the-pitch',true),
  ('Capitol Riverfront BID','bid_riverfront_friday_night_concert_series_ft_the_dc_transit_band_2026-07-31','Friday Night Concert Series ft. The DC Transit Band','Free summer concert on the Yards Park boardwalk.','concerts','Concerts',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-07-31','6:30 PM',(timestamp '2026-07-31 18:30:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/friday-night-concert-series-aug-01-2026','https://navyyarddc.org/event/friday-night-concert-series-aug-01-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_wellness_on_the_water_2026-08-01','Wellness on the Water','A waterfront fitness and wellness series at Yards Park.','fitness','Fitness',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-01',null,null,'Free','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_wellness_on_the_water_2026-08-08','Wellness on the Water','A waterfront fitness and wellness series at Yards Park.','fitness','Fitness',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-08',null,null,'Free','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_wellness_on_the_water_2026-08-22','Wellness on the Water','A waterfront fitness and wellness series at Yards Park.','fitness','Fitness',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-22',null,null,'Free','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_wellness_on_the_water_2026-09-05','Wellness on the Water','A waterfront fitness and wellness series at Yards Park.','fitness','Fitness',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-09-05',null,null,'Free','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_wellness_on_the_water_2026-09-12','Wellness on the Water','A waterfront fitness and wellness series at Yards Park.','fitness','Fitness',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-09-12',null,null,'Free','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026','https://navyyarddc.org/event/wellness-on-the-water-aug-01-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_dpr_movies_on_the_great_lawn_super_mario_galaxy_2026-08-06','DPR Movies on the Great Lawn: Super Mario Galaxy','Free family movie night on the Great Lawn with a slime-making activity.','community','Community',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-06','6:00 PM',(timestamp '2026-08-06 18:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/dpr-movies-on-the-great-lawn-super-mario-galaxy','https://navyyarddc.org/event/dpr-movies-on-the-great-lawn-super-mario-galaxy',true),
  ('Capitol Riverfront BID','bid_riverfront_princess_diaries_on_the_pitch_2026-08-06','Princess Diaries on the Pitch','An outdoor screening of The Princess Diaries on the Audi Field pitch.','community','Community',array['Navy Yard'],'Audi Field','Audi Field','Audi Field, 100 Potomac Ave SW, Washington, DC','Navy Yard',date '2026-08-06','8:00 PM',(timestamp '2026-08-06 20:00:00' at time zone 'America/New_York'),null,'https://navyyarddc.org/event/movies-on-the-pitch-3a823','https://navyyarddc.org/event/movies-on-the-pitch-3a823',false),
  ('Capitol Riverfront BID','bid_riverfront_friday_night_concert_series_ft_perfekt_blend_2026-08-07','Friday Night Concert Series ft. Perfekt Blend','Free high-energy Top 40 and Motown from Perfekt Blend at Yards Park.','concerts','Concerts',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-07','6:30 PM',(timestamp '2026-08-07 18:30:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/friday-night-concert-series-jul-17-2026','https://navyyarddc.org/event/friday-night-concert-series-jul-17-2026',true),
  ('Capitol Riverfront BID','bid_riverfront_dpr_movies_on_the_great_lawn_smurfs_lost_village_2026-08-13','DPR Movies on the Great Lawn: Smurfs Lost Village','Free family movie night on the Great Lawn with a craft activity.','community','Community',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-13','6:00 PM',(timestamp '2026-08-13 18:00:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/dpr-movies-on-the-great-lawn-smurfs-lost-village','https://navyyarddc.org/event/dpr-movies-on-the-great-lawn-smurfs-lost-village',true),
  ('Capitol Riverfront BID','bid_riverfront_wellness_on_the_water_with_britt_daniels_2026-08-15','Wellness on the Water with Britt Daniels','An R&B flow class with intentional movement and vendor activations at Yards Park.','fitness','Fitness',array['Navy Yard','Free'],'Yards Park','Yards Park','Yards Park, 355 Water St SE, Washington, DC','Navy Yard',date '2026-08-15','8:30 AM',(timestamp '2026-08-15 08:30:00' at time zone 'America/New_York'),'Free','https://navyyarddc.org/event/wellness-on-the-water-britt','https://navyyarddc.org/event/wellness-on-the-water-britt',true),
  ('Southwest BID','bid_sw_art_rx_weaving_reveal_2026-08-05','Art RX Weaving Reveal','A reveal of Kelsey Merreck Wagner''s recycled-material tree weavings around the Duck Pond.','community','Community',array['Southwest','Free'],'Southwest Duck Pond','Southwest Duck Pond','Southwest Duck Pond, 900 6th St SW, Washington, DC','Southwest',date '2026-08-05','12:00 PM',(timestamp '2026-08-05 12:00:00' at time zone 'America/New_York'),'Free','https://swbid.org/event/art-rx-weaving-reveal/','https://swbid.org/event/art-rx-weaving-reveal/',true),
  ('Southwest BID','bid_sw_10th_anniversary_of_community_tables_2026-08-09','10th Anniversary of Community Tables','A milestone Community Tables celebration with hands-on activities, poetry and a shared meal.','community','Community',array['Southwest','Free'],'Southwest Duck Pond','Southwest Duck Pond','Southwest Duck Pond, 900 6th St SW, Washington, DC','Southwest',date '2026-08-09','4:00 PM',(timestamp '2026-08-09 16:00:00' at time zone 'America/New_York'),'Free','https://swbid.org/event/10th-community-tables/','https://swbid.org/event/10th-community-tables/',true);

on conflict (source, external_id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  tag = excluded.tag,
  tags = excluded.tags,
  venue_name = excluded.venue_name,
  venue = excluded.venue,
  venue_address = excluded.venue_address,
  neighborhood = excluded.neighborhood,
  date = excluded.date,
  time = excluded.time,
  starts_at = excluded.starts_at,
  price = excluded.price,
  ticket_url = excluded.ticket_url,
  external_url = excluded.external_url,
  is_free = excluded.is_free,
  last_seen_at = now(),
  updated_at = now();
