create table if not exists public.onboarding_submissions (
  id bigint generated by default as identity primary key,
  user_key text not null,
  account_type text not null default 'person',
  full_name text,
  username text,
  email text,
  phone text,
  birthdate date,
  event_interests text[] not null default '{}',
  area_interests text[] not null default '{}',
  venue_name text,
  venue_address text,
  venue_website text,
  venue_image_url text,
  venue_description text,
  created_at timestamptz not null default now()
);

create index if not exists onboarding_submissions_user_key_idx
  on public.onboarding_submissions(user_key);

create index if not exists onboarding_submissions_account_type_idx
  on public.onboarding_submissions(account_type);

alter table public.onboarding_submissions enable row level security;

drop policy if exists "Anyone can submit onboarding"
  on public.onboarding_submissions;

create policy "Anyone can submit onboarding"
  on public.onboarding_submissions
  for insert
  to anon, authenticated
  with check (true);
