create table if not exists public.friend_relationships (
  id bigint generated by default as identity primary key,
  user_key text not null,
  friend_name text not null,
  status text not null default 'accepted',
  source text not null default 'demo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists friend_relationships_user_friend_idx
  on public.friend_relationships (user_key, friend_name);

create table if not exists public.group_memberships (
  id bigint generated by default as identity primary key,
  user_key text not null,
  group_name text not null,
  member_name text not null,
  role text not null default 'member',
  status text not null default 'active',
  source text not null default 'demo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists group_memberships_user_group_member_idx
  on public.group_memberships (user_key, group_name, member_name);

create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  user_key text not null,
  group_name text not null,
  message_type text not null default 'text',
  message_text text,
  event_id text,
  created_at timestamptz not null default now()
);

create index if not exists group_messages_user_group_idx
  on public.group_messages (user_key, group_name, created_at desc);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  user_key text not null,
  friend_name text not null,
  direction text not null default 'outbound',
  message_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists direct_messages_user_friend_idx
  on public.direct_messages (user_key, friend_name, created_at desc);

alter table public.friend_relationships enable row level security;
alter table public.group_memberships enable row level security;
alter table public.group_messages enable row level security;
alter table public.direct_messages enable row level security;

grant select, insert, update on public.friend_relationships to anon, authenticated;
grant select, insert, update on public.group_memberships to anon, authenticated;
grant select, insert on public.group_messages to anon, authenticated;
grant select, insert on public.direct_messages to anon, authenticated;

drop policy if exists "friend_relationships_insert_demo" on public.friend_relationships;
create policy "friend_relationships_insert_demo"
  on public.friend_relationships for insert
  to anon, authenticated
  with check (true);

drop policy if exists "friend_relationships_select_demo" on public.friend_relationships;
create policy "friend_relationships_select_demo"
  on public.friend_relationships for select
  to anon, authenticated
  using (true);

drop policy if exists "friend_relationships_update_demo" on public.friend_relationships;
create policy "friend_relationships_update_demo"
  on public.friend_relationships for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "group_memberships_insert_demo" on public.group_memberships;
create policy "group_memberships_insert_demo"
  on public.group_memberships for insert
  to anon, authenticated
  with check (true);

drop policy if exists "group_memberships_select_demo" on public.group_memberships;
create policy "group_memberships_select_demo"
  on public.group_memberships for select
  to anon, authenticated
  using (true);

drop policy if exists "group_memberships_update_demo" on public.group_memberships;
create policy "group_memberships_update_demo"
  on public.group_memberships for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "group_messages_insert_demo" on public.group_messages;
create policy "group_messages_insert_demo"
  on public.group_messages for insert
  to anon, authenticated
  with check (true);

drop policy if exists "direct_messages_insert_demo" on public.direct_messages;
create policy "direct_messages_insert_demo"
  on public.direct_messages for insert
  to anon, authenticated
  with check (true);
