create table if not exists public.venue_follows (
  id bigint generated by default as identity primary key,
  user_key text not null,
  venue_name text not null,
  active boolean not null default true,
  source text not null default 'event_detail',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists venue_follows_user_venue_idx
  on public.venue_follows (user_key, venue_name);

create index if not exists venue_follows_venue_active_idx
  on public.venue_follows (venue_name, active);

alter table public.venue_follows enable row level security;

grant select, insert, update on public.venue_follows to anon, authenticated;

drop policy if exists "venue_follows_select_demo" on public.venue_follows;
create policy "venue_follows_select_demo"
  on public.venue_follows for select
  to anon, authenticated
  using (true);

drop policy if exists "venue_follows_insert_demo" on public.venue_follows;
create policy "venue_follows_insert_demo"
  on public.venue_follows for insert
  to anon, authenticated
  with check (true);

drop policy if exists "venue_follows_update_demo" on public.venue_follows;
create policy "venue_follows_update_demo"
  on public.venue_follows for update
  to anon, authenticated
  using (true)
  with check (true);
