create table if not exists public.venue_verification_requests (
  id bigint generated by default as identity primary key,
  requester_user_id text not null,
  requester_name text,
  requester_email text,
  requester_phone text,
  venue_name text not null,
  venue_address text not null,
  venue_website text,
  requester_role text,
  notes text,
  status text not null default 'pending',
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists venue_verification_requests_status_idx
  on public.venue_verification_requests(status);

create index if not exists venue_verification_requests_user_idx
  on public.venue_verification_requests(requester_user_id);

alter table public.venue_verification_requests enable row level security;

drop policy if exists "Anyone can request venue verification"
  on public.venue_verification_requests;

create policy "Anyone can request venue verification"
  on public.venue_verification_requests
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Approved venue requests are readable by the app"
  on public.venue_verification_requests;

create policy "Approved venue requests are readable by the app"
  on public.venue_verification_requests
  for select
  to anon, authenticated
  using (status = 'approved');

create table if not exists public.venue_event_submissions (
  id bigint generated by default as identity primary key,
  requester_user_id text not null,
  venue_name text not null,
  venue_address text,
  title text not null,
  description text,
  category text not null default 'community',
  tags text[] not null default '{}',
  starts_at timestamptz not null,
  ends_at timestamptz,
  image_url text,
  ticket_url text,
  price text,
  is_recurring boolean not null default false,
  recurrence_frequency text,
  recurrence_until date,
  status text not null default 'pending_review',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists venue_event_submissions_status_idx
  on public.venue_event_submissions(status);

create index if not exists venue_event_submissions_venue_idx
  on public.venue_event_submissions(venue_name);

alter table public.venue_event_submissions enable row level security;

drop policy if exists "Verified venues can submit event drafts"
  on public.venue_event_submissions;

create policy "Verified venues can submit event drafts"
  on public.venue_event_submissions
  for insert
  to anon, authenticated
  with check (true);
